Feat/add dockerfile
cloudnativedaysjp/dreamkast-weaver pull request #5
Opened 2023-04-20 14:55 UTC by ystkfujii

2023-04-20 15:48 UTC, ystkfujii commented
@どなたか

レビューお願いします～

2023-04-22 10:22 UTC, inductor commented on dockerfiles/initdb.dockerfile
> +ENTRYPOINT ["/initdb"]
Add EOL
![Uploading image.png…]()

2023-04-22 10:23 UTC, inductor commented on dockerfiles/serve.dockerfile
> +ENTRYPOINT ["/serve"]
Ditto

2023-04-22 10:24 UTC, inductor requested changes
ファイルの最後にEOLを入れるように、エディタの設定を入れておきましょう。
https://chaika.hatenablog.com/entry/2019/09/11/083000

2023-04-23 03:07 UTC, ystkfujii commented
> ファイルの最後にEOLを入れるように、エディタの設定を入れておきましょう。

設定入って無かったです 🙇 
案内ありがとうございます :thanks:

2023-04-23 03:08 UTC, ystkfujii commented on dockerfiles/initdb.dockerfile
> +ENTRYPOINT ["/initdb"]
対応しました！

2023-04-23 10:20 UTC, inductor commented on Makefile
> +	docker push $(REGISTRY_SERVE):$(VERSION)
EOF

2023-04-23 10:21 UTC, inductor commented on dockerfiles/initdb.dockerfile
> +FROM alpine:3.17.3
Use https://github.com/GoogleContainerTools/distroless/blob/main/base/README.md ?

2023-04-23 10:21 UTC, inductor commented on dockerfiles/serve.dockerfile
> +FROM alpine:3.17.3
Ditto

2023-04-23 10:24 UTC, inductor commented on dev/compose.yaml
> -      DB_NAME: dkui
DB名って消えて問題ない？

2023-04-23 11:34 UTC, ystkfujii commented on dev/compose.yaml
> -      DB_NAME: dkui
DB名はハードコードしており、その値はみてないので大丈夫です。

FYI：
- 読み込んでる箇所：https://github.com/cloudnativedaysjp/dreamkast-weaver/blob/12ca6410089411b249d8d40ed8da9b0e6b49eebb/internal/sqlhelper/sqlhelper.go#L36
- ハードコードしている理由：https://github.com/cloudnativedaysjp/dreamkast-weaver/pull/2#issuecomment-1510377531

2023-04-23 11:37 UTC, ystkfujii commented on dockerfiles/initdb.dockerfile
> +FROM alpine:3.17.3
コメントありがとうございます 🙇 
Destrolessイメージに変更しました。

そして大変参考になりました 🙏 
https://blog.inductor.me/entry/alpine-not-recommended

2023-04-23 11:37 UTC, ystkfujii commented on Makefile
> +	docker push $(REGISTRY_SERVE):$(VERSION)
🙇

2023-04-23 11:42 UTC, inductor commented
@ystkfujii コンテナイメージっていつ作る感じですか？（ビルド処理とか動作確認とかやれてるのかなという確認）

2023-04-23 12:36 UTC, ystkfujii commented
@inductor 
> @ystkfujii コンテナイメージっていつ作る感じですか？

手元でビルドしてECRにプッシ済みです。EKSからpullしてきて動作することは確認しています。

CIの組み込みですが、アカウント何使っていいのか詰めれてなくて、実装していない感じです。その他にも足りてない部分(tagとか)ありますが、その他の細かいとこはEKS上で動かしながら確認しようかなと思っています。

2023-04-23 13:02 UTC, inductor commented
@ystkfujii 
> 本当はCIにイメージビルド組み込みたいのですが、アカウント何使っていいのか詰めれてなくて、実装していない感じです。

push: falseにしてDockerのbuild push actionはもう動かせるはずなので、やったほうがいいです。

https://github.com/cloudnativedaysjp/dreamkast/blob/main/.github/workflows/build.yml あたり参考にしてみて。

2023-04-23 15:52 UTC, ystkfujii commented
@inductor 
> push: falseにしてDockerのbuild push actionはもう動かせるはずなので、やったほうがいい

たしかにそうですね。追加しました 🙇

2023-04-23 17:42 UTC, inductor commented on .github/workflows/build-serve.yml
> +          go-version-file: 'go.mod'
Docker buildのアクションにset up goは不要かも？

2023-04-24 03:36 UTC, ystkfujii commented on .github/workflows/build-serve.yml
> +          go-version-file: 'go.mod'
すみません、完全に勘違いしてました。中でgolangのimage使ってるのでレイヤーが違いますね 🙏

2023-04-24 22:32 UTC, inductor reviewed
ビルドのアクションってmatrixとかで共通化できない感じ？

2023-04-24 22:32 UTC, inductor commented on .github/workflows/build-initdb.yml
> +          push: false # TODO ture
typo

2023-04-25 14:54 UTC, ystkfujii commented on .github/workflows/build-initdb.yml
> +          push: false # TODO ture
🙏

2023-04-25 14:55 UTC, ystkfujii commented
@inductor 
> ビルドのアクションってmatrixとかで共通化できない感じ？

コメントありがとうございます。
なるほど、こういう機能があるんですね。matrixを使用することでかなりシンプルになりました 🙇

2023-04-25 16:17 UTC, hrk091 reviewed
initdb周り中心にいくつかコメントしました。

2023-04-25 16:17 UTC, hrk091 commented on tools/initdb/main.go
> +//go:build tools
この処理内容なら、 `ghcr.io/amacneil/dbmate` イメージを使ってbashで実行しても良さそうですが、コンテナ実装を選択した理由は何かありますか？
ビルド・デプロイするもろもろの手間が省けて、DBマイグレーションの内容がマニフェストだけに凝集されるので、その方が楽な気がしました

2023-04-25 16:17 UTC, hrk091 commented on tools/initdb/main.go
> +		fmt.Printf("connecting %s ... \n", u)
パスワードが標準出力に出てしまうので、パスワードは除いたほうが良さそうです。

2023-04-25 16:17 UTC, hrk091 commented on dockerfiles/serve.dockerfile
> +RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -tags timetzdata -a -o serve cmd/serve/main.go
GOOS、GOARCHはARGにした方が良さそうです。ARM対応もありえますし。
（default値は今のままで大丈夫です）

2023-04-25 16:17 UTC, hrk091 commented on .github/workflows/build.yml
> +      - name: Build
（ただのコメントです）
image buildはgoreleaser使えばいいかなと思っていたのですが、今回はバイナリビルド不要なので、 `docker/build-push-action` で良さそうですね

2023-04-25 16:27 UTC, ystkfujii commented on tools/initdb/main.go
> +//go:build tools
そこは悩みでした。。。  
dbmateのimageを使用すると、Manifestにdatabase名(cfp/dkui)を書かないといけない認識です。それよりはコンテナ実装してManifest側でdatabase名を意識させない方が良いのかなと考え、この実装を選択しました。

2023-04-25 16:35 UTC, ystkfujii commented on dockerfiles/serve.dockerfile
> +RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -tags timetzdata -a -o serve cmd/serve/main.go
> -a を付けてるのは何か狙いがありますか？

ここは下記を参考にした感じです。

https://github.com/cloudnativedaysjp/seaman/blob/303dbe29f99ee13518f4cd1c9ef25d1204b9eb88/Dockerfile#L17

古いキャッシュを参照するケースはよく分からなかったのですが、安全のためにつけました

2023-04-25 16:40 UTC, ystkfujii commented on tools/initdb/main.go
> +//go:build tools
あぁ、Makefileでまとめて叩けばいいだけなのか... 🤔

2023-04-25 18:50 UTC, ystkfujii commented on tools/initdb/main.go
> +//go:build tools
`ghcr.io/amacneil/dbmate`イメージにmigrationファイル＆migration実行シェルスクリプトをマウントしたイメージを作っておいて、それをinitContainerとして使う感じでしょうか？

2023-04-26 15:58 UTC, hrk091 commented on tools/initdb/main.go
> +//go:build tools
あと、initdb用のコマンドを別imageでbuildするのがめんどい問題については、serveとinitdbをサブコマンドにし、一つのimageで両方たたけるようにする作戦もありだと思います。（何かしらのCLIフレームワークを使って。例えばcobraとか https://github.com/spf13/cobra）

2023-05-03 17:24 UTC, ystkfujii commented on tools/initdb/main.go
> +//go:build tools
> 一つのimageで両方たたけるようにする作戦もありだと思います

initdbスクリプトの場合、podへ各migration folderのマウントが必須であり、良い回避策が思いつかないため、提案頂いた1つのimageにまとめる作成でいきたいと思います。

下記コミットで対応しました

- https://github.com/cloudnativedaysjp/dreamkast-weaver/pull/5/commits/afd220212131c1abc5efb062fde344fb32ac19c8
- https://github.com/cloudnativedaysjp/dreamkast-weaver/pull/5/commits/e6deb90843f6c41868e55c0efe72e0506102e824
- https://github.com/cloudnativedaysjp/dreamkast-weaver/pull/5/commits/3d9da5e3fc727f3c1319f2176ec5378e9743a477

2023-05-03 17:24 UTC, ystkfujii commented on tools/initdb/main.go
> +		fmt.Printf("connecting %s ... \n", u)
これは恥ずかしいやつですね。。。削除しました 🙏

2023-05-03 17:26 UTC, ystkfujii commented on tools/initdb/main.go
> +			migrationDir: "/internal/dkui/db/migrations",
カレントディレクトリを取得してパスを結合するように修正しました。

https://github.com/cloudnativedaysjp/dreamkast-weaver/pull/5/commits/71cc67209c0aebc2373d1282d17a6caafa66d61a

2023-05-03 17:27 UTC, ystkfujii commented on dockerfiles/serve.dockerfile
> +RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -tags timetzdata -a -o serve cmd/serve/main.go
対応しました。`-a`は古いキャッシュを参照するケースがよく分からなかったので削除しました。

2023-05-06 05:01 UTC, hrk091 approved these changes
ご対応ありがとうございます！！LGTMです。
細かなところ少しだけコメントしましたが、修正するか否かはおまかせします！

2023-05-06 06:05 UTC, inductor commented
@ystkfujii https://github.com/cloudnativedaysjp/dreamkast-weaver/pull/5/commits/a45f4905bdf7d2101950edbb59f3617f8dd04bb3 https://github.com/cloudnativedaysjp/dreamkast-weaver/pull/5/commits/29817374e5eb484cfa752028a56454625942a346 を追加しておいたので見てください。

2023-05-07 07:50 UTC, ystkfujii commented on cmd/dkw/dbmigrate.go
> +		wd, err := os.Getwd()
go.modはバイナリ実行時には存在しないので、migration dirの存在確認を追加しました

2023-05-07 07:58 UTC, ystkfujii commented on cmd/main.go
> +package main
移動させました。また、dbmigrate/serveをモジュールとして読み込む必要があるので、man.goの移動に伴い、`dbmigrate`/`serve`パッケージを作成しました。それと、役割が重複していると感じたので、`main.go`と`root.go`は統合しました。

2023-05-07 08:14 UTC, ystkfujii commented
@inductor 

> https://github.com/cloudnativedaysjp/dreamkast-weaver/commit/a45f4905bdf7d2101950edbb59f3617f8dd04bb3 https://github.com/cloudnativedaysjp/dreamkast-weaver/commit/29817374e5eb484cfa752028a56454625942a346 を追加しておいたので見てください。

めっっっっっちゃ勉強になります 🙏 

[pre-defined annotation key](https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys)というものがあるんですね 👀 
`--link`オプションもしりませんでした。。。ありがとうございます 🙇

2023-05-07 08:28 UTC, merged